### ISSUE TITLE
k8s

### ISSUE THREAD

**Issue by ysl2** [ysl2/blog#16]
https://golangguide.top/%E6%9E%B6%E6%9E%84/%E4%BA%91%E5%8E%9F%E7%94%9F/%E6%A0%B8%E5%BF%83%E7%9F%A5%E8%AF%86%E7%82%B9/k8s%E5%88%B0%E5%BA%95%E6%98%AF%E4%BB%80%E4%B9%88.html

**Comment by ysl2** [comment]
[Kubernetes-Cheat-Sheet.pdf](https://github.com/user-attachments/files/15753272/Kubernetes-Cheat-Sheet.pdf)

**Comment by ysl2** [comment]
```
kubectl get pods --all-namespaces
kubectl get pods -A

kubectl get pods -n <namespace>
kubectl get deployment -n <namespace>
kubectl get replicaset -n <namespace>

kubectl exec -it ysl-5c8cc9ddd9-q9zq6 -n my-namespace -- /bin/bash
```

**Comment by ysl2** [comment]
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ysl-check-env-new
  namespace: ysl-newnamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ysl-check-env-new
  template:
    metadata:
      labels:
        app: ysl-check-env-new
    spec:
      containers:
      - name: ysl-check-env-new
        image: registry.abcde.com/fgh/ijk-tools-x86:latest
```
`kubectl apply -f deployment.yaml`
